apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: helm-kubescape
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: '>=v1.0.6'
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: Installs the Kubescape Operator Helm chart for CIS/NSA/MITRE compliance
    scanning.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # helm-kubescape

    Installs the Kubescape Operator Helm chart using Crossplane and the Helm provider.
    Kubescape is a CNCF project for Kubernetes security posture management.
  repository: ghcr.io/hops-ops/helm-kubescape
  source: github.com/hops-ops/helm-kubescape
